POST http://localhost:8000/usuario HTTP/1.1
Content-Type:  application/json

{
    "nome": "nome teste",
    "senha": "123"
}

###
GET  http://localhost:8000/usuario HTTP/1.1
Content-Type:  application/json


###
GET  http://localhost:8000/usuario/082e33e2-d92b-4360-b484-e7ab50ca1159 HTTP/1.1
Content-Type:  application/json


###
PUT   http://localhost:8000/usuario/082e33e2-d92b-4360-b484-e7ab50ca1159 HTTP/1.1
Content-Type:  application/json

{
    "nome": "other_name",
    "senha": "$2a$10$fYpsD09cFp6YUfYQE2/z6u6Rz1DMZPNQcALMMRkI8VwtYQrvMjOKy",
    "ativo": true
}

###
DELETE    http://localhost:8000/usuario/082e33e2-d92b-4360-b484-e7ab50ca1159 HTTP/1.1
Content-Type:  application/json
