POST http://localhost:8000/usuario HTTP/1.1
Content-Type:  application/json

{
    "nome": "nome4",
    "senha": "123"
}

###
GET  http://localhost:8000/usuario HTTP/1.1
Content-Type:  application/json


###
GET  http://localhost:8000/usuario/4c54400c-d139-444e-8917-72f21be9ad41 HTTP/1.1
Content-Type:  application/json


###
PUT   http://localhost:8000/usuario/4c54400c-d139-444e-8917-72f21be9ad41 HTTP/1.1
Content-Type:  application/json

{
    "nome": "other_name",
    "senha": "$2a$10$fYpsD09cFp6YUfYQE2/z6u6Rz1DMZPNQcALMMRkI8VwtYQrvMjOKy",
    "ativo": true
}

###
DELETE    http://localhost:8000/usuario/4c54400c-d139-444e-8917-72f21be9ad41 HTTP/1.1
Content-Type:  application/json

###
GET  http://localhost:8000/usuario/paginado?pagina=1&limit=2 HTTP/1.1
Content-Type:  application/json
